name: fbtm-action
description: an action used to automatically manage fbtm repositories
author: brxxn
inputs:
  github-token:
    description: GitHub token with write permissions to repo and issues
    required: true
  block-main-branch-push:
    description: block pushing to the main branch (use for experimental actions)
    required: true
    default: false
runs:
  using: node20
  main: dist/index.js